version: '3.8'
services:
  app:
    build: .
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: videoDB
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
